// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuJmt-sNx0TVvAFgaipxKxCHrabXSjE0o',
    appId: '1:675530154893:web:e95ddb0a0eddb324d813c4',
    messagingSenderId: '675530154893',
    projectId: 'heartland-strength-app',
    authDomain: 'heartland-strength-app.firebaseapp.com',
    storageBucket: 'heartland-strength-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXvD440A3Xo7j0KEgAphVNCIzgUKDwIo',
    appId: '1:675530154893:android:e5b8d81940fce559d813c4',
    messagingSenderId: '675530154893',
    projectId: 'heartland-strength-app',
    storageBucket: 'heartland-strength-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGubIMhZiWs7v0WztL_PuaN_J6X_DxGdY',
    appId: '1:675530154893:ios:f07b9cd2d10e5aaad813c4',
    messagingSenderId: '675530154893',
    projectId: 'heartland-strength-app',
    storageBucket: 'heartland-strength-app.firebasestorage.app',
    iosBundleId: 'com.example.heartlandstrengthapp',
  );
}
